# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c308a5ea90d2347851097cedddc5ce3b54f0e63071dd58d510fd15de9139622909f55c300c96d2869147505bbd66d1060a5a27a7c2a6215f3c6a42b6868dd1

test:
  secret_key_base: ebb3ee67737640c8b0ffb6bea8c7e622aae396c49b2b71c5d2790d0d69cbf23bf3edb6aaaf5652539755fdf8b547777cd11deebc8c965af12f819b2fbbe00b1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
